# Default values for minifi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: apache/nifi-minifi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0.0-M2"

# config.yml settings
minifiConfigVersion: 3
flowControllerName: MiNiFi Flow
coreProperties:
  flowControllerGracefulShutdowPeriod: 10 sec
  flowServiceWriteDelayInterval: 500 ms
  administrativeYieldDuration: 30 sec
  boredYieldDuration: 10 millis
  maxConcurrentThreads: 1
flowFileRepository:
  partitions: 256
  checkpointInterval: 2 mins
  alwaysSync: false
  swap:
    threshold: 20000
    inPeriod: 5 sec
    inThreads: 1
    outPeriod: 5 sec
    outThreads: 4
contentRepository:
  contentClaimMaxAppendableSize: 10 MB
  contentClaimMaxFlowFiles: 100
  alwaysSync: false
provenanceRepository:
  provenanceRolloverTime: 1 min
componentStatusRepository:
  bufferSize: 1440
  snapshotFrequency: 1 min
securityProperties:
  keystore: ''
  keystoreType: ''
  keystorePassword: ''
  keyPassword: ''
  truststore: ''
  truststoreType: ''
  truststorePassword: ''
  sslProtocol: ''
  sensitiveProps:
    key: ''
    algorithm: NIFI_PBKDF2_AES_GCM_256 
processors: |-

  - name: Get files from /tmp/
    id: 2f2a3b47-f5ba-49f6-82b5-bc1c86b96e27
    class: org.apache.nifi.processors.standard.GetFile
    scheduling strategy: TIMER_DRIVEN
    scheduling period: 1000 ms
    Properties:
      Input Directory: /tmp/getfile_dir
      Keep Source File: 'true'
      Recurse Subdirectories: 'true'
      Ignore Hidden Files: 'false'
  - name: FTP Files away
    id: e143601d-de4f-44ba-a6ec-d1f97d77ec94
    class: org.apache.nifi.processors.standard.PutFTP
    scheduling strategy: TIMER_DRIVEN
    scheduling period: 1000 ms
    auto-terminated relationships list:
    - failure
    - success
    - reject
    Properties:
      Hostname: 192.168.2.202
      Port: 21
      Username: hassio
      Password: FTP-PASSWORD
      Create Directory: true
      Batch Size: 500
      Connection TImeout: 30 sec
      Data Timeout: 30 sec
      Conflict Resolution: REPLACE


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
